import type { Card } from "@/types";

// cardTemplates.ts
export const cardTemplates: Omit<Card, "id">[] = [
    {
        title: "Flame Imp",
        description: "Deal 3 damage to your hero.",
        mana: 1,
        attack: 3,
        health: 2,
        type: "Demon",
        imageUrl: "https://placehold.co/300x200/orange/white?text=Flame+Imp",
    },
    {
        title: "Chillwind Yeti",
        description: "A solid yeti.",
        mana: 4,
        attack: 4,
        health: 5,
        type: "Beast",
        imageUrl: "https://placehold.co/300x200/cyan/white?text=Yeti",
    },
    {
        title: "Fireball",
        description: "Deal 6 damage.",
        mana: 4,
        attack: undefined,
        health: undefined,
        type: "Spell",
        imageUrl: "https://placehold.co/300x200/red/white?text=Fireball",
    },
    {
        title: "Arcane Intellect",
        description: "Draw 2 cards.",
        mana: 3,
        imageUrl: "https://placehold.co/300x200/blue/white?text=Intellect",
        type: "Spell",
    },
    {
        title: "Boulderfist Ogre",
        description: "Big, dumb, strong.",
        mana: 6,
        attack: 6,
        health: 7,
        type: "Ogre",
        imageUrl: "https://placehold.co/300x200/purple/white?text=Ogre",
    },
    {
        title: "Wolfrider",
        description: "Charge.",
        mana: 3,
        attack: 3,
        health: 1,
        type: "Beast",
        imageUrl: "https://placehold.co/300x200/gray/white?text=Wolfrider",
    },
    {
        title: "Frostbolt",
        description: "Deal 3 damage and Freeze.",
        mana: 2,
        type: "Spell",
        imageUrl: "https://placehold.co/300x200/lightblue/black?text=Frostbolt",
    },
    {
        title: "Bloodfen Raptor",
        description: "Just a raptor.",
        mana: 2,
        attack: 3,
        health: 2,
        type: "Beast",
        imageUrl: "https://placehold.co/300x200/green/white?text=Raptor",
    },
    {
        title: "River Crocolisk",
        description: "Swampy and snappy.",
        mana: 2,
        attack: 2,
        health: 3,
        type: "Beast",
        imageUrl: "https://placehold.co/300x200/brown/white?text=Crocolisk",
    },
    {
        title: "Ironfur Grizzly",
        description: "Taunt.",
        mana: 3,
        attack: 3,
        health: 3,
        type: "Beast",
        imageUrl: "https://placehold.co/300x200/tan/black?text=Grizzly",
    },
];
