import type {
  Card,
  DamageEffect,
  DivineShieldEffect,
  EffectTypes,
} from "@/types";

const damage = (
  value: number | keyof Card,
  target: DamageEffect["target"] = "user-select",
  battlecry: boolean = false,
): EffectTypes => {
  return {
    type: "damage",
    value: value,
    target: target,
    battlecry: battlecry,
  };
};

const freeze = (
  target: DamageEffect["target"] = "user-select",
  battlecry: boolean = false,
): EffectTypes => {
  return {
    type: "freeze",
    target: target,
    battlecry: battlecry,
  };
};

const divineShield = (
  target: DivineShieldEffect["target"] = "user-select",
  battlecry: boolean = false,
): EffectTypes => {
  return {
    type: "divineShield",
    target: target,
    battlecry: battlecry,
  };
};

const destroy = (
  target: "user-select" | "self" | "enemy-board",
  battlecry: boolean = false,
): EffectTypes => {
  return {
    type: "destroy",
    target: target,
    battlecry: battlecry,
  };
};

const mana = (value: number): EffectTypes => {
  return { type: "mana", value: value };
};
const heal = (
  value: number,
  target:
    | "user-select"
    | "friendly-hero"
    | "friendly-all"
    | "friendly-board" = "user-select",
  battlecry: boolean = false,
): EffectTypes => {
  return {
    type: "heal",
    value: value,
    target: target,
    battlecry: battlecry,
  };
};

const draw = (value: number): EffectTypes => {
  return {
    type: "draw",
    value: value,
  };
};

const changeKey = (
  key: keyof Card,
  value: any,
  target: "user-select" | "self" = "self",
): EffectTypes => {
  return {
    type: "changeKey",
    key: key,
    value: value,
    target: target,
  };
};

const incrementValue = (
  key: keyof Card,
  value: number,
  target: "user-select" | "self" = "user-select",
): EffectTypes => {
  return {
    type: "incrementValue",
    key: key,
    value: value,
    target: target,
  };
};

const summon = (cardID: string): EffectTypes => {
  return {
    type: "summon",
    cardID: cardID,
  };
};

// cardTemplates.ts
export const cardTemplates = {
  "flame-imp": {
    title: "Flame Imp",
    description: "Deal 3 damage to your hero.",
    mana: 1,
    attack: 3,
    health: 2,
    type: "Demon",
    imageUrl: "assets/cards/Flame_Imp.jpg",
    effects: [damage("attack")],
    onPlace: [damage(3, "friendly-hero")],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Warlock",
  },
  "chillwind-yeti": {
    title: "Chillwind Yeti",
    description: "A solid yeti.",
    mana: 4,
    attack: 4,
    health: 5,
    type: "Beast",
    imageUrl: "assets/cards/Chillwind_Yeti.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  fireball: {
    title: "Fireball",
    description: "Deal 6 damage.",
    mana: 4,
    attack: undefined,
    health: undefined,
    type: "Spell",
    imageUrl: "assets/cards/fireball.jpg",
    effects: [damage(6)],
    onPlace: [],
    isSpell: true,
    targets: ["card", "player"],
    isMinion: false,
    class: "Mage",
  },
  "arcane-intellect": {
    title: "Arcane Intellect",
    description: "Draw 2 cards.",
    mana: 3,
    imageUrl: "assets/cards/Arcane_Intellect.jpg",
    type: "Spell",
    effects: [draw(2)],
    onPlace: [],
    isSpell: true,
    targets: [], // Can target the player to draw cards
    isMinion: false,
    class: "Mage",
  },
  "boulderfist-ogre": {
    title: "Boulderfist Ogre",
    description: "",
    mana: 6,
    attack: 6,
    health: 7,
    imageUrl: "assets/cards/Boulderfist_Ogre_full.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  wolfrider: {
    title: "Wolfrider",
    description: "Charge.",
    mana: 3,
    attack: 3,
    health: 1,
    type: "Beast",
    imageUrl: "assets/cards/Wolfrider.jpg",
    effects: [damage("attack")],
    onPlace: [changeKey("summoningSickness", false, "self")],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  frostbolt: {
    title: "Frostbolt",
    description: "Deal 3 damage and Freeze.",
    mana: 2,
    type: "Spell",
    imageUrl: "assets/cards/Frostbolt.jpg",
    effects: [damage(3), freeze()],
    onPlace: [],
    isSpell: true,
    targets: ["card", "player"],
    isMinion: false,
    class: "Mage",
  },
  "bloodfen-raptor": {
    title: "Bloodfen Raptor",
    description: "",
    mana: 2,
    attack: 3,
    health: 2,
    type: "Beast",
    imageUrl: "assets/cards/Bloodfen_Raptor.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "river-crocolisk": {
    title: "River Crocolisk",
    description: "",
    mana: 2,
    attack: 2,
    health: 3,
    type: "Beast",
    imageUrl: "assets/cards/River_Crocolisk.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "ironfur-grizzly": {
    title: "Ironfur Grizzly",
    description: "Taunt.",
    taunt: true,
    mana: 3,
    attack: 3,
    health: 3,
    type: "Beast",
    imageUrl: "assets/cards/Ironfur_Grizzly.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  charge: {
    title: "Charge",
    description: "Give a minion Charge.",
    mana: 1,
    type: "Spell",
    imageUrl: "assets/cards/Charge.jpg",
    effects: [changeKey("summoningSickness", false)],
    onPlace: [],
    isSpell: true,
    isMinion: false,
    targets: ["card-friendly"],
    class: "Warrior",
  },
  "murloc-raider": {
    title: "Murloc Raider",
    description: "",
    attack: 2,
    health: 1,
    mana: 1,
    type: "Murloc",
    imageUrl: "assets/cards/Murloc_Raider.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "frostwolf-grunt": {
    title: "Frostwolf Grunt",
    description: "Taunt.",
    taunt: true,
    attack: 2,
    health: 2,
    mana: 2,
    imageUrl: "assets/cards/Frostwolf_Grunt.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "murloc-tidehunter": {
    title: "Murloc Tidehunter",
    description: "Battlecry: Summons a 1/1 Murloc Scout.",
    attack: 2,
    health: 1,
    mana: 2,
    type: "Murloc",
    imageUrl: "assets/cards/Murloc_Raider.jpg",
    effects: [damage("attack")],
    onPlace: [summon("murloc-scout")],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "murloc-scout": {
    title: "Murloc Scout",
    description: "A small murloc.",
    attack: 1,
    health: 1,
    mana: 1,
    type: "Murloc",
    imageUrl: "assets/cards/Murloc_Raider.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    isUncollectible: true,
    class: "Neutral",
  },
  "razorfen-hunter": {
    title: "Razorfen Hunter",
    description: "Battlecry: Summons a 1/1 Boar.",
    attack: 2,
    health: 3,
    mana: 3,
    imageUrl: "assets/cards/Razorfen_Hunter.jpg",
    effects: [damage("attack")],
    onPlace: [summon("boar")],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  boar: {
    title: "Boar",
    description: "A wild boar.",
    attack: 1,
    health: 1,
    mana: 1,
    type: "Beast",
    imageUrl: "assets/cards/Boar.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    isUncollectible: true,
    class: "Neutral",
  },
  "dragonling-mechanic": {
    title: "Dragonling Mechanic",
    description: "Battlecry: Summons a 2/1 Mechanical Dragonling.",
    attack: 2,
    health: 4,
    mana: 4,
    imageUrl: "assets/cards/Dragonling_Mechanic.jpg",
    effects: [damage("attack")],
    onPlace: [summon("mechanical-dragonling")],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "mechanical-dragonling": {
    title: "Mechanical Dragonling",
    description: "A mechanical dragonling.",
    attack: 2,
    health: 1,
    mana: 2,
    type: "Mechanical",
    imageUrl: "assets/cards/Mechanical_Dragonling.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    isUncollectible: true,
    class: "Neutral",
  },
  "senjin-shieldmasta": {
    title: "Sen'jin Shieldmasta",
    description: "Taunt.",
    taunt: true,
    attack: 3,
    health: 5,
    mana: 4,
    imageUrl: "assets/cards/Senjin_Shieldmasta.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "lord-of-the-arena": {
    title: "Lord of the Arena",
    description: "Taunt.",
    taunt: true,
    attack: 6,
    health: 5,
    mana: 6,
    imageUrl: "assets/cards/Lord_of_the_Arena.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "stormwind-knight": {
    title: "Stormwind Knight",
    description: "Taunt.",
    taunt: false,
    attack: 2,
    health: 5,
    mana: 4,
    imageUrl: "assets/cards/Stormwind_Knight.jpg",
    effects: [damage("attack")],
    onPlace: [changeKey("summoningSickness", false, "self")],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  innervate: {
    title: "Innervate",
    description: "Gain 2 Mana Crystal this turn only.",
    mana: 0,
    type: "Spell",
    imageUrl: "assets/cards/Innervate.jpg",
    effects: [mana(2)],
    onPlace: [],
    isSpell: true,
    targets: [],
    isMinion: false,
    class: "Druid",
  },
  "mark-of-the-wild": {
    title: "Mark of the Wild",
    description: "Give a minion +2/+3 and Taunt.",
    mana: 2,
    type: "Spell",
    imageUrl: "assets/cards/Mark_of_the_Wild.jpg",
    effects: [
      incrementValue("attack", 2),
      incrementValue("maxAttack", 2),
      incrementValue("health", 3),
      incrementValue("maxHealth", 3),
      changeKey("taunt", true),
    ],
    onPlace: [],
    isSpell: true,
    targets: ["card-friendly"],
    isMinion: false,
    class: "Druid",
  },
  "healing-touch": {
    title: "Healing Touch",
    description: "Restore 8 Health.",
    mana: 3,
    type: "Spell",
    imageUrl: "assets/cards/Healing_Touch.jpg",
    effects: [heal(8)],
    onPlace: [],
    isSpell: true,
    targets: ["card-friendly", "player-friendly"],
    isMinion: false,
    class: "Druid",
  },
  "darkscale-healer": {
    title: "Darkscale Healer",
    description: "Battlecry: Restore 2 Health to all friendly characters.",
    attack: 4,
    health: 5,
    mana: 5,
    type: "Naga",
    imageUrl: "assets/cards/Darkscale_Healer.jpg",
    effects: [damage("attack")],
    onPlace: [heal(2, "friendly-all", true)],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  nightblade: {
    title: "Nightblade",
    description: "Deal 3 damage to the enemy hero.",
    attack: 4,
    health: 4,
    mana: 5,
    type: "Human",
    imageUrl: "assets/cards/Nightblade.jpg",
    effects: [damage("attack")],
    onPlace: [damage(3, "enemy-hero")],
    targets: ["player-opponent", "card-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "elven-archer": {
    title: "Elven Archer",
    description: "Battlecry: Deal 1 damage.",
    attack: 1,
    health: 1,
    mana: 1,
    imageUrl: "assets/cards/Elven_Archer.jpg",
    effects: [damage("attack")],
    onPlace: [damage(1, "user-select", true)], // Battlecry damage that can target any character, bypassing taunt
    targets: ["card-opponent", "player-opponent"],
    battlecryTargets: ["card-opponent", "player-opponent"], // Can target any character for battlecry damage
    isMinion: true,
    class: "Neutral",
  },
  "ironforge-rifleman": {
    title: "Ironforge Rifleman",
    description: "Battlecry: Deal 1 damage.",
    attack: 2,
    health: 2,
    mana: 3,
    imageUrl: "assets/cards/Ironforge_Rifleman.jpg",
    effects: [damage("attack")],
    onPlace: [damage(1, "user-select", true)],
    targets: ["card-opponent", "player-opponent"],
    battlecryTargets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "core-hound": {
    title: "Core Hound",
    attack: 9,
    health: 7,
    mana: 7,
    type: "Beast",
    description: "",
    imageUrl: "assets/cards/Core_Hound.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "silverback-patriarch": {
    title: "Silverback Patriarch",
    description: "Taunt.",
    taunt: true,
    attack: 1,
    health: 4,
    mana: 3,
    type: "Beast",
    imageUrl: "assets/cards/Silverback_Patriarch.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "magma-rager": {
    title: "Magma Rager",
    description: "",
    mana: 3,
    attack: 5,
    health: 1,
    type: "Elemental",
    imageUrl: "assets/cards/Magma_Rager.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "oasis-snapjaw": {
    title: "Oasis Snapjaw",
    description: "",
    mana: 4,
    attack: 2,
    health: 7,
    type: "Beast",
    imageUrl: "assets/cards/Oasis_Snapjaw.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "silver-hand-knight": {
    title: "Silver Hand Knight",
    description: "Battlecry: Summon a 2/2 Squire.",
    mana: 5,
    attack: 4,
    health: 4,
    type: "Human",
    imageUrl: "assets/cards/Silver_Hand_Knight.jpg",
    effects: [damage("attack")],
    onPlace: [summon("squire")],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  squire: {
    title: "Squire",
    description: "Ready for battle.",
    mana: 1,
    attack: 2,
    health: 2,
    type: "Human",
    imageUrl: "assets/cards/Squire.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    isUncollectible: true,
    class: "Neutral",
  },
  "voodoo-doctor": {
    title: "Voodoo Doctor",
    description: "Battlecry: Restore 2 Health.",
    mana: 1,
    attack: 2,
    health: 1,
    imageUrl: "assets/cards/Voodoo_Doctor.jpg",
    effects: [damage("attack")],
    onPlace: [heal(2)], // Reuses your healing-touch payload architecture on a targeted entity
    battlecryTargets: ["card-friendly", "player-friendly"], // Can target friendly characters for battlecry healing
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    hasAttacked: false,
    class: "Neutral",
  },
  "novice-engineer": {
    title: "Novice Engineer",
    description: "Battlecry: Draw a card.",
    mana: 2,
    attack: 1,
    health: 1,
    imageUrl: "assets/cards/Novice_Engineer.jpg",
    effects: [damage("attack")],
    onPlace: [draw(1)], // Draw a card when placed
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "stormpike-commando": {
    title: "Stormpike Commando",
    description: "Battlecry: Deal 2 damage.",
    mana: 5,
    attack: 4,
    health: 2,
    imageUrl: "assets/cards/Stormpike_Commando.jpg",
    effects: [damage("attack")],
    onPlace: [damage(2, "user-select", true)], // Uses elven archer battlecry logic scaled to 2
    targets: ["card-opponent", "player-opponent"],
    battlecryTargets: ["card-opponent", "player-opponent"], // Can target any character for battlecry damage
    isMinion: true,
    hasAttacked: false,
    class: "Neutral",
  },
  "gnomish-inventor": {
    title: "Gnomish Inventor",
    description: "Battlecry: Draw a card.",
    mana: 4,
    attack: 2,
    health: 4,
    imageUrl: "assets/cards/Gnomish_Inventor.jpg",
    effects: [damage("attack")],
    onPlace: [draw(1)], // Draw a card when placed
    battlecryTargets: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "arcane-shot": {
    title: "Arcane Shot",
    description: "Deal 2 damage.",
    mana: 1,
    effects: [damage(2)],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isSpell: true,
    isMinion: false,
    imageUrl: "assets/cards/Arcane_Shot.jpg",
    class: "Hunter",
  },
  assassinate: {
    title: "Assassinate",
    description: "Destroy an enemy minion.",
    mana: 5,
    effects: [destroy("user-select")], // Targeted destroy effect that can target any minion, bypassing taunt
    onPlace: [],
    targets: ["card-opponent"], // Can only target opponent minions
    isSpell: true,
    isMinion: false,
    imageUrl: "assets/cards/Assassinate.jpg",
    class: "Rogue",
  },
  "blessing-of-kings": {
    title: "Blessing of Kings",
    description: "Give a minion +4/+4.",
    mana: 4,
    type: "Holy",
    imageUrl: "assets/cards/Blessing_of_Kings.jpg",
    effects: [
      incrementValue("attack", 4),
      incrementValue("maxAttack", 4),
      incrementValue("health", 4),
      incrementValue("maxHealth", 4),
    ],
    onPlace: [],
    isSpell: true,
    targets: ["card-friendly"],
    isMinion: false,
    class: "Paladin",
  },
  "goldshire-footman": {
    title: "Goldshire Footman",
    description: "Taunt.",
    taunt: true,
    attack: 1,
    health: 2,
    mana: 1,
    imageUrl: "assets/cards/Goldshire_Footman.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "booty-bay-bodyguard": {
    title: "Booty Bay Bodyguard",
    description: "Taunt.",
    taunt: true,
    attack: 5,
    health: 4,
    mana: 5,
    imageUrl: "assets/cards/Booty_Bay_Bodyguard.jpg",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "reckless-rocketeer": {
    title: "Reckless Rocketeer",
    description: "Charge.",
    mana: 6,
    attack: 5,
    health: 2,
    imageUrl: "assets/cards/Reckless_Rocketeer.jpg",
    effects: [damage("attack")],
    onPlace: [changeKey("summoningSickness", false, "self")],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Neutral",
  },
  "inner-rage": {
    title: "Inner Rage",
    imageUrl: "assets/cards/Inner_Rage.jpg",
    description: "Deal 1 damage to a minion and give it +2 Attack.",
    mana: 0,
    effects: [
      damage(1),
      incrementValue("attack", 2),
      incrementValue("maxAttack", 2),
    ],
    onPlace: [],
    targets: ["card-friendly", "card-opponent"],
    isSpell: true,
    isMinion: false,
    class: "Warrior",
  },
  "bluegill-warrior": {
    title: "Bluegill Warrior",
    description: "Charge.",
    mana: 2,
    attack: 2,
    health: 1,
    type: "Murloc",
    imageUrl: "assets/cards/Bluegill_Warrior.jpg",
    effects: [damage("attack")],
    onPlace: [changeKey("summoningSickness", false, "self")],
    targets: ["card-opponent", "player-opponent"],
    isMinion: true,
    class: "Warrior",
  },
  flamestrike: {
    title: "Flamestrike",
    imageUrl: "assets/cards/Flamestrike.jpg",
    description: "Deal 5 damage to all enemy minions.",
    mana: 7,
    effects: [damage(5, "enemy-board")],
    onPlace: [],
    targets: ["lane-opponent", "lane-friendly"],
    isSpell: true,
    isMinion: false,
    class: "Mage",
  },
  "leper-gnome": {
    title: "Leper Gnome",
    imageUrl: "assets/cards/Leper_Gnome.jpg",
    description: "Deathrattle: Deal 2 damage to the enemy hero.",
    mana: 1,
    attack: 2,
    health: 1,
    isMinion: true,
    class: "Neutral",
    targets: ["card-opponent", "player-opponent"],
    effects: [damage("attack")],
    onPlace: [],
    deathrattle: [damage(2, "enemy-hero")],
  },
  "loot-hoarder": {
    title: "Loot Hoarder",
    imageUrl: "assets/cards/Loot_Hoarder.jpg",
    description: "Deathrattle: Draw a card.",
    mana: 2,
    attack: 2,
    health: 1,
    isMinion: true,
    class: "Neutral",
    targets: ["card-opponent", "player-opponent"],
    effects: [damage("attack")],
    onPlace: [],
    deathrattle: [draw(1)],
  },
  "argent-squire": {
    title: "Argent Squire",
    imageUrl: "assets/cards/Argent_Squire.jpg",
    description: "Divine Shield.",
    mana: 1,
    attack: 1,
    health: 1,

    isMinion: true,
    divineShield: true, // Spawns with the effect active
    class: "Neutral",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
  },
  shielded_minibot: {
    title: "Shielded Minibot",
    description: "Divine Shield",
    imageUrl: "assets/cards/Shielded_Minibot.jpg",
    mana: 2,
    attack: 2,
    health: 2,
    type: "Mech",
    isMinion: true,
    divineShield: true,
    class: "Paladin",
    effects: [damage("attack")],
    onPlace: [],
    targets: ["card-opponent", "player-opponent"],
  },
  "tirion-fordring": {
    title: "Tirion Fordring",
    imageUrl: "assets/cards/Tirion_Fordring.jpg",
    description: "Divine Shield, Taunt, Deathrattle: Equip a 5/3 Ashbringer.",
    mana: 8,
    attack: 8,
    health: 8,
    isMinion: true,
    taunt: true,
    divineShield: true,
    class: "Paladin",
    targets: ["card-opponent", "player-opponent"],
    effects: [damage("attack")],
    onPlace: [],
  },
  sunwalker: {
    title: "Sunwalker",
    description: "Taunt. Divine Shield.",
    imageUrl: "assets/cards/Sunwalker.jpg",
    mana: 6,
    attack: 4,
    health: 5,
    isMinion: true,
    taunt: true, // Forces enemies to attack this card
    divineShield: true, // Absorbs the first attack completely
    class: "Neutral",
    targets: ["card-opponent", "player-opponent"],
    effects: [damage("attack")],
    onPlace: [],
  },
  "argent-protector": {
    title: "Argent Protector",
    description: "Battlecry: guve a friendly minion Divine Shield.",
    imageUrl: "assets/cards/Argent_Protector.jpg",
    mana: 2,
    attack: 2,
    health: 2,
    isMinion: true,
    taunt: false,
    divineShield: false,
    class: "Paladin",
    targets: ["card-opponent", "player-opponent"],
    effects: [damage("attack")],
    onPlace: [divineShield("user-select", true)],
    battlecryTargets: ["card-friendly"],
  },
  "hand-of-protection": {
    title: "Hand of Protection",
    description: "Give a minion Divine Shield.",
    mana: 1,
    attack: undefined,
    health: undefined,
    type: "Spell",
    imageUrl: "assets/cards/Hand_of_Protection.jpg",
    effects: [divineShield("user-select")],
    onPlace: [],
    isSpell: true,
    targets: ["card"],
    isMinion: false,
    class: "Paladin",
  },
} satisfies Record<string, Omit<Card, "id">>;

// 1. Automatically extracts: "flame-imp" | "chillwind-yeti" | ...
export type CardTemplateKey = keyof typeof cardTemplates;

// 2. An actual type-safe Record mapping your exact keys to cards
export type CardTemplateRecord = typeof cardTemplates;
